
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xconv2d.h"

/*
* The configuration table for devices
*/

XConv2d_Config XConv2d_ConfigTable[XPAR_XCONV2D_NUM_INSTANCES] =
{
	{
		XPAR_CONV2D_0_DEVICE_ID,
		XPAR_CONV2D_0_S_AXI_CONTROL_BASEADDR
	}
};


