// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="conv2d_conv2d,hls_ip_2022_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.256000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=3231,HLS_SYN_LUT=3288,HLS_VERSION=2022_2}" *)

module conv2d (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x,
        weight,
        bias,
        width,
        height,
        in_channels,
        out_channels,
        ksize,
        y,
        y_ap_vld
);

parameter    ap_ST_fsm_state1 = 15'd1;
parameter    ap_ST_fsm_state2 = 15'd2;
parameter    ap_ST_fsm_state3 = 15'd4;
parameter    ap_ST_fsm_state4 = 15'd8;
parameter    ap_ST_fsm_state5 = 15'd16;
parameter    ap_ST_fsm_state6 = 15'd32;
parameter    ap_ST_fsm_state7 = 15'd64;
parameter    ap_ST_fsm_state8 = 15'd128;
parameter    ap_ST_fsm_state9 = 15'd256;
parameter    ap_ST_fsm_state10 = 15'd512;
parameter    ap_ST_fsm_state11 = 15'd1024;
parameter    ap_ST_fsm_state12 = 15'd2048;
parameter    ap_ST_fsm_state13 = 15'd4096;
parameter    ap_ST_fsm_state14 = 15'd8192;
parameter    ap_ST_fsm_state15 = 15'd16384;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] x;
input  [31:0] weight;
input  [31:0] bias;
input  [31:0] width;
input  [31:0] height;
input  [31:0] in_channels;
input  [31:0] out_channels;
input  [31:0] ksize;
output  [31:0] y;
output   y_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg y_ap_vld;

(* fsm_encoding = "none" *) reg   [14:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [0:0] tmp_reg_549;
reg   [30:0] p_lshr_f_reg_554;
wire   [63:0] zext_ln20_fu_190_p1;
wire   [63:0] grp_fu_194_p2;
reg   [63:0] mul_ln20_reg_575;
wire    ap_CS_fsm_state2;
wire   [63:0] grp_fu_208_p2;
reg   [63:0] mul_ln20_2_reg_581;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire  signed [32:0] sext_ln23_fu_305_p1;
reg  signed [32:0] sext_ln23_reg_617;
wire    ap_CS_fsm_state7;
wire  signed [32:0] height_cast_fu_309_p1;
reg  signed [32:0] height_cast_reg_623;
wire   [31:0] empty_fu_312_p1;
reg   [31:0] empty_reg_628;
wire   [31:0] grp_fu_168_p2;
reg   [31:0] mul_reg_633;
wire   [95:0] grp_fu_241_p2;
reg   [95:0] mul_ln20_1_reg_638;
wire   [95:0] grp_fu_254_p2;
reg   [95:0] mul_ln20_3_reg_643;
wire   [0:0] icmp_ln27_1_fu_316_p2;
reg   [0:0] icmp_ln27_1_reg_648;
wire   [0:0] icmp_ln35_fu_321_p2;
reg   [0:0] icmp_ln35_reg_653;
wire   [30:0] select_ln25_fu_392_p3;
reg   [30:0] select_ln25_reg_661;
wire    ap_CS_fsm_state8;
wire   [0:0] icmp_ln23_fu_341_p2;
wire   [30:0] select_ln25_1_fu_400_p3;
reg   [30:0] select_ln25_1_reg_667;
wire   [32:0] sub_ln25_fu_435_p2;
reg   [32:0] sub_ln25_reg_673;
wire    ap_CS_fsm_state9;
wire   [31:0] trunc_ln25_fu_441_p1;
reg   [31:0] trunc_ln25_reg_678;
wire   [32:0] sub_ln38_fu_449_p2;
reg   [32:0] sub_ln38_reg_683;
wire   [31:0] trunc_ln38_fu_455_p1;
reg   [31:0] trunc_ln38_reg_688;
wire   [0:0] rev94_fu_465_p2;
reg   [0:0] rev94_reg_693;
wire    grp_conv2d_Pipeline_in_channels_kh_kw_fu_147_ap_start;
wire    grp_conv2d_Pipeline_in_channels_kh_kw_fu_147_ap_done;
wire    grp_conv2d_Pipeline_in_channels_kh_kw_fu_147_ap_idle;
wire    grp_conv2d_Pipeline_in_channels_kh_kw_fu_147_ap_ready;
wire   [31:0] grp_conv2d_Pipeline_in_channels_kh_kw_fu_147_sum_2_out;
wire    grp_conv2d_Pipeline_in_channels_kh_kw_fu_147_sum_2_out_ap_vld;
wire   [31:0] grp_conv2d_Pipeline_in_channels_kh_kw_fu_147_grp_fu_164_p_din0;
wire   [31:0] grp_conv2d_Pipeline_in_channels_kh_kw_fu_147_grp_fu_164_p_din1;
wire   [1:0] grp_conv2d_Pipeline_in_channels_kh_kw_fu_147_grp_fu_164_p_opcode;
wire    grp_conv2d_Pipeline_in_channels_kh_kw_fu_147_grp_fu_164_p_ce;
reg    grp_conv2d_Pipeline_in_channels_kh_kw_fu_147_ap_start_reg;
wire    ap_CS_fsm_state10;
reg   [30:0] w_fu_72;
wire   [30:0] add_ln27_fu_472_p2;
reg   [30:0] h_fu_76;
reg   [63:0] indvar_flatten42_fu_80;
wire   [63:0] select_ln25_2_fu_414_p3;
reg   [95:0] indvar_flatten67_fu_84;
wire   [95:0] add_ln23_fu_346_p2;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state15;
reg   [31:0] grp_fu_164_p0;
reg   [31:0] grp_fu_164_p1;
wire   [31:0] grp_fu_168_p0;
wire   [31:0] grp_fu_168_p1;
wire   [31:0] grp_fu_194_p0;
wire   [31:0] grp_fu_194_p1;
wire  signed [31:0] zext_ln20_3_fu_200_p0;
wire   [31:0] grp_fu_208_p0;
wire   [31:0] grp_fu_208_p1;
wire   [31:0] grp_fu_241_p0;
wire   [63:0] grp_fu_241_p1;
wire   [31:0] grp_fu_254_p0;
wire   [63:0] grp_fu_254_p1;
wire   [31:0] p_neg_fu_270_p2;
wire   [30:0] p_lshr_fu_275_p4;
wire   [31:0] p_lshr_cast_fu_285_p1;
wire   [31:0] p_neg_t_fu_289_p2;
wire   [31:0] p_lshr_f_cast_fu_295_p1;
wire   [31:0] div_fu_298_p3;
wire  signed [31:0] height_cast_fu_309_p0;
wire   [31:0] zext_ln27_1_fu_332_p1;
wire   [0:0] icmp_ln25_fu_358_p2;
wire   [0:0] icmp_ln27_fu_336_p2;
wire   [30:0] select_ln23_fu_363_p3;
wire   [0:0] select_ln23_2_fu_379_p3;
wire   [30:0] select_ln23_1_fu_371_p3;
wire   [30:0] add_ln25_fu_386_p2;
wire   [63:0] add_ln25_1_fu_408_p2;
wire   [32:0] zext_ln25_fu_432_p1;
wire   [32:0] zext_ln27_fu_446_p1;
wire   [0:0] slt_fu_460_p2;
wire   [31:0] grp_fu_164_p2;
reg    grp_fu_164_ce;
reg   [14:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire   [63:0] grp_fu_208_p00;
wire   [63:0] grp_fu_208_p10;
wire   [95:0] grp_fu_241_p00;
wire   [95:0] grp_fu_241_p10;
wire   [95:0] grp_fu_254_p00;
wire   [95:0] grp_fu_254_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 15'd1;
#0 grp_conv2d_Pipeline_in_channels_kh_kw_fu_147_ap_start_reg = 1'b0;
end

conv2d_conv2d_Pipeline_in_channels_kh_kw grp_conv2d_Pipeline_in_channels_kh_kw_fu_147(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_conv2d_Pipeline_in_channels_kh_kw_fu_147_ap_start),
    .ap_done(grp_conv2d_Pipeline_in_channels_kh_kw_fu_147_ap_done),
    .ap_idle(grp_conv2d_Pipeline_in_channels_kh_kw_fu_147_ap_idle),
    .ap_ready(grp_conv2d_Pipeline_in_channels_kh_kw_fu_147_ap_ready),
    .sext_ln25(sub_ln25_reg_673),
    .sext_ln23_2(height),
    .p_cast_mid2(trunc_ln25_reg_678),
    .mul_ln20_1(mul_ln20_1_reg_638),
    .mul_ln20(mul_ln20_reg_575),
    .cmp31_mid122(rev94_reg_693),
    .ksize(ksize),
    .icmp_ln35_1(icmp_ln35_reg_653),
    .sext_ln38(sub_ln38_reg_683),
    .trunc_ln(trunc_ln38_reg_688),
    .sext_ln23_1(width),
    .mul(mul_reg_633),
    .sum_2_out(grp_conv2d_Pipeline_in_channels_kh_kw_fu_147_sum_2_out),
    .sum_2_out_ap_vld(grp_conv2d_Pipeline_in_channels_kh_kw_fu_147_sum_2_out_ap_vld),
    .grp_fu_164_p_din0(grp_conv2d_Pipeline_in_channels_kh_kw_fu_147_grp_fu_164_p_din0),
    .grp_fu_164_p_din1(grp_conv2d_Pipeline_in_channels_kh_kw_fu_147_grp_fu_164_p_din1),
    .grp_fu_164_p_opcode(grp_conv2d_Pipeline_in_channels_kh_kw_fu_147_grp_fu_164_p_opcode),
    .grp_fu_164_p_dout0(grp_fu_164_p2),
    .grp_fu_164_p_ce(grp_conv2d_Pipeline_in_channels_kh_kw_fu_147_grp_fu_164_p_ce)
);

conv2d_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_164_p0),
    .din1(grp_fu_164_p1),
    .ce(grp_fu_164_ce),
    .dout(grp_fu_164_p2)
);

conv2d_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U16(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_168_p0),
    .din1(grp_fu_168_p1),
    .ce(1'b1),
    .dout(grp_fu_168_p2)
);

conv2d_mul_32ns_32ns_64_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_2_1_U17(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_194_p0),
    .din1(grp_fu_194_p1),
    .ce(1'b1),
    .dout(grp_fu_194_p2)
);

conv2d_mul_32ns_32ns_64_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_2_1_U18(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_208_p0),
    .din1(grp_fu_208_p1),
    .ce(1'b1),
    .dout(grp_fu_208_p2)
);

conv2d_mul_32ns_64ns_96_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 96 ))
mul_32ns_64ns_96_5_1_U19(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_241_p0),
    .din1(grp_fu_241_p1),
    .ce(1'b1),
    .dout(grp_fu_241_p2)
);

conv2d_mul_32ns_64ns_96_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 96 ))
mul_32ns_64ns_96_5_1_U20(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_254_p0),
    .din1(grp_fu_254_p1),
    .ce(1'b1),
    .dout(grp_fu_254_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_conv2d_Pipeline_in_channels_kh_kw_fu_147_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_conv2d_Pipeline_in_channels_kh_kw_fu_147_ap_start_reg <= 1'b1;
        end else if ((grp_conv2d_Pipeline_in_channels_kh_kw_fu_147_ap_ready == 1'b1)) begin
            grp_conv2d_Pipeline_in_channels_kh_kw_fu_147_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        h_fu_76 <= 31'd0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        h_fu_76 <= select_ln25_1_reg_667;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten42_fu_80 <= 64'd0;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln23_fu_341_p2 == 1'd0))) begin
        indvar_flatten42_fu_80 <= select_ln25_2_fu_414_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten67_fu_84 <= 96'd0;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln23_fu_341_p2 == 1'd0))) begin
        indvar_flatten67_fu_84 <= add_ln23_fu_346_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        w_fu_72 <= 31'd0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        w_fu_72 <= add_ln27_fu_472_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        empty_reg_628 <= empty_fu_312_p1;
        height_cast_reg_623 <= height_cast_fu_309_p1;
        icmp_ln27_1_reg_648 <= icmp_ln27_1_fu_316_p2;
        icmp_ln35_reg_653 <= icmp_ln35_fu_321_p2;
        mul_ln20_1_reg_638 <= grp_fu_241_p2;
        mul_ln20_3_reg_643 <= grp_fu_254_p2;
        mul_reg_633 <= grp_fu_168_p2;
        sext_ln23_reg_617 <= sext_ln23_fu_305_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        mul_ln20_2_reg_581 <= grp_fu_208_p2;
        mul_ln20_reg_575 <= grp_fu_194_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        p_lshr_f_reg_554 <= {{ksize[31:1]}};
        tmp_reg_549 <= ksize[32'd31];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        rev94_reg_693 <= rev94_fu_465_p2;
        sub_ln25_reg_673 <= sub_ln25_fu_435_p2;
        sub_ln38_reg_683 <= sub_ln38_fu_449_p2;
        trunc_ln25_reg_678 <= trunc_ln25_fu_441_p1;
        trunc_ln38_reg_688 <= trunc_ln38_fu_455_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln23_fu_341_p2 == 1'd0))) begin
        select_ln25_1_reg_667 <= select_ln25_1_fu_400_p3;
        select_ln25_reg_661 <= select_ln25_fu_392_p3;
    end
end

always @ (*) begin
    if ((grp_conv2d_Pipeline_in_channels_kh_kw_fu_147_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln23_fu_341_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln23_fu_341_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_164_ce = grp_conv2d_Pipeline_in_channels_kh_kw_fu_147_grp_fu_164_p_ce;
    end else begin
        grp_fu_164_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_164_p0 = grp_conv2d_Pipeline_in_channels_kh_kw_fu_147_grp_fu_164_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_164_p0 = grp_conv2d_Pipeline_in_channels_kh_kw_fu_147_sum_2_out;
    end else begin
        grp_fu_164_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_164_p1 = grp_conv2d_Pipeline_in_channels_kh_kw_fu_147_grp_fu_164_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_164_p1 = empty_reg_628;
    end else begin
        grp_fu_164_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        y_ap_vld = 1'b1;
    end else begin
        y_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln23_fu_341_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (grp_conv2d_Pipeline_in_channels_kh_kw_fu_147_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln23_fu_346_p2 = (indvar_flatten67_fu_84 + 96'd1);

assign add_ln25_1_fu_408_p2 = (indvar_flatten42_fu_80 + 64'd1);

assign add_ln25_fu_386_p2 = (select_ln23_fu_363_p3 + 31'd1);

assign add_ln27_fu_472_p2 = (select_ln25_reg_661 + 31'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign div_fu_298_p3 = ((tmp_reg_549[0:0] == 1'b1) ? p_neg_t_fu_289_p2 : p_lshr_f_cast_fu_295_p1);

assign empty_fu_312_p1 = bias;

assign grp_conv2d_Pipeline_in_channels_kh_kw_fu_147_ap_start = grp_conv2d_Pipeline_in_channels_kh_kw_fu_147_ap_start_reg;

assign grp_fu_168_p0 = x;

assign grp_fu_168_p1 = weight;

assign grp_fu_194_p0 = zext_ln20_fu_190_p1;

assign grp_fu_194_p1 = zext_ln20_fu_190_p1;

assign grp_fu_208_p0 = grp_fu_208_p00;

assign grp_fu_208_p00 = $unsigned(zext_ln20_3_fu_200_p0);

assign grp_fu_208_p1 = grp_fu_208_p10;

assign grp_fu_208_p10 = width;

assign grp_fu_241_p0 = grp_fu_241_p00;

assign grp_fu_241_p00 = in_channels;

assign grp_fu_241_p1 = grp_fu_241_p10;

assign grp_fu_241_p10 = mul_ln20_reg_575;

assign grp_fu_254_p0 = grp_fu_254_p00;

assign grp_fu_254_p00 = out_channels;

assign grp_fu_254_p1 = grp_fu_254_p10;

assign grp_fu_254_p10 = mul_ln20_2_reg_581;

assign height_cast_fu_309_p0 = height;

assign height_cast_fu_309_p1 = height_cast_fu_309_p0;

assign icmp_ln23_fu_341_p2 = ((indvar_flatten67_fu_84 == mul_ln20_3_reg_643) ? 1'b1 : 1'b0);

assign icmp_ln25_fu_358_p2 = ((indvar_flatten42_fu_80 == mul_ln20_2_reg_581) ? 1'b1 : 1'b0);

assign icmp_ln27_1_fu_316_p2 = (($signed(width) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln27_fu_336_p2 = (($signed(zext_ln27_1_fu_332_p1) < $signed(width)) ? 1'b1 : 1'b0);

assign icmp_ln35_fu_321_p2 = ((ksize == 32'd0) ? 1'b1 : 1'b0);

assign p_lshr_cast_fu_285_p1 = p_lshr_fu_275_p4;

assign p_lshr_f_cast_fu_295_p1 = p_lshr_f_reg_554;

assign p_lshr_fu_275_p4 = {{p_neg_fu_270_p2[31:1]}};

assign p_neg_fu_270_p2 = (32'd0 - ksize);

assign p_neg_t_fu_289_p2 = (32'd0 - p_lshr_cast_fu_285_p1);

assign rev94_fu_465_p2 = (slt_fu_460_p2 ^ 1'd1);

assign select_ln23_1_fu_371_p3 = ((icmp_ln25_fu_358_p2[0:0] == 1'b1) ? 31'd0 : w_fu_72);

assign select_ln23_2_fu_379_p3 = ((icmp_ln25_fu_358_p2[0:0] == 1'b1) ? icmp_ln27_1_reg_648 : icmp_ln27_fu_336_p2);

assign select_ln23_fu_363_p3 = ((icmp_ln25_fu_358_p2[0:0] == 1'b1) ? 31'd0 : h_fu_76);

assign select_ln25_1_fu_400_p3 = ((select_ln23_2_fu_379_p3[0:0] == 1'b1) ? select_ln23_fu_363_p3 : add_ln25_fu_386_p2);

assign select_ln25_2_fu_414_p3 = ((icmp_ln25_fu_358_p2[0:0] == 1'b1) ? 64'd1 : add_ln25_1_fu_408_p2);

assign select_ln25_fu_392_p3 = ((select_ln23_2_fu_379_p3[0:0] == 1'b1) ? select_ln23_1_fu_371_p3 : 31'd0);

assign sext_ln23_fu_305_p1 = $signed(div_fu_298_p3);

assign slt_fu_460_p2 = (($signed(sub_ln25_fu_435_p2) < $signed(height_cast_reg_623)) ? 1'b1 : 1'b0);

assign sub_ln25_fu_435_p2 = ($signed(zext_ln25_fu_432_p1) - $signed(sext_ln23_reg_617));

assign sub_ln38_fu_449_p2 = ($signed(zext_ln27_fu_446_p1) - $signed(sext_ln23_reg_617));

assign trunc_ln25_fu_441_p1 = sub_ln25_fu_435_p2[31:0];

assign trunc_ln38_fu_455_p1 = sub_ln38_fu_449_p2[31:0];

assign y = grp_fu_164_p2;

assign zext_ln20_3_fu_200_p0 = height;

assign zext_ln20_fu_190_p1 = ksize;

assign zext_ln25_fu_432_p1 = select_ln25_1_reg_667;

assign zext_ln27_1_fu_332_p1 = w_fu_72;

assign zext_ln27_fu_446_p1 = select_ln25_reg_661;

endmodule //conv2d
